### ISSUE TITLE
Include channel in the message callback

### ISSUE THREAD

**Issue by vicary** [faye/faye#409] opened 2015-10-16 04:02 UTC
When working with wildcard channels like `/foo/**`, it is very likely that the callback need to know where the message is sent exactly.

```javascript
client.subscribe('/foo/**', function(message, channel) {
  console.log('Message %s from channel %s', JSON.stringify(message), channel);
});
```

A general use case could be a drop-in handler that stores messages into database.

**Comment by jcoglan** [comment] 2015-10-18 11:21
This is a duplicate of #385 -- could you take a look at that and comment if you have any info we've not considered yet? Thanks :)

**Closed by jcoglan** 2015-10-18 11:21 UTC

**Comment by vicary** [comment] 2015-10-18 18:48
Was not aware of the lengthy conversation, it reveals many design considerations behind the scene. Since it is going exactly the way I wanted, I'll leave it for you guys. Thanks for the good work. ;)
