### ISSUE TITLE
Incredible big session

### ISSUE THREAD

**Issue by toomus** [faye/faye#421] opened 2016-02-03 13:12 UTC
Hi. I have some weird problem in my Rails app. After this messages:

```
**** INCOMING ****
{"channel"=>"/meta/connect", "clientId"=>"ahhhyccl5tra4cv5g1kp76oawqw0zvu", "connectionType"=>"websocket", "id"=>"5", "ext"=>{"user_id"=>215, "realtime_events_token"=>"ef32a222-0e58-41da-8b59-b7b49bbfdb64"}}

**** OUTGOING ****
{"id"=>"5", "clientId"=>"ahhhyccl5tra4cv5g1kp76oawqw0zvu", "channel"=>"/meta/connect", "successful"=>true, "advice"=>{"reconnect"=>"retry", "interval"=>0, "timeout"=>25000}}
```
session size is ~50MB. When I disable faye in browser, session size is ~50KB. Is this normal? And why client connects so many times?
```
**** OUTGOING ****
{"id"=>"d", "clientId"=>"ahhhyccl5tra4cv5g1kp76oawqw0zvu", "channel"=>"/meta/connect", "successful"=>true, "advice"=>{"reconnect"=>"retry", "interval"=>0, "timeout"=>25000}}

**** INCOMING ****
{"channel"=>"/meta/connect", "clientId"=>"ahhhyccl5tra4cv5g1kp76oawqw0zvu", "connectionType"=>"websocket", "id"=>"e", "ext"=>{"user_id"=>215, "realtime_events_token"=>"ef32a222-0e58-41da-8b59-b7b49bbfdb64"}}

**** OUTGOING ****
{"id"=>"e", "clientId"=>"ahhhyccl5tra4cv5g1kp76oawqw0zvu", "channel"=>"/meta/connect", "successful"=>true, "advice"=>{"reconnect"=>"retry", "interval"=>0, "timeout"=>25000}}

**** INCOMING ****
{"channel"=>"/meta/connect", "clientId"=>"ahhhyccl5tra4cv5g1kp76oawqw0zvu", "connectionType"=>"websocket", "id"=>"f", "ext"=>{"user_id"=>215, "realtime_events_token"=>"ef32a222-0e58-41da-8b59-b7b49bbfdb64"}}

**** OUTGOING ****
{"id"=>"f", "clientId"=>"ahhhyccl5tra4cv5g1kp76oawqw0zvu", "channel"=>"/meta/connect", "successful"=>true, "advice"=>{"reconnect"=>"retry", "interval"=>0, "timeout"=>25000}}

**** INCOMING ****
{"channel"=>"/meta/connect", "clientId"=>"ahhhyccl5tra4cv5g1kp76oawqw0zvu", "connectionType"=>"websocket", "id"=>"f", "ext"=>{"user_id"=>215, "realtime_events_token"=>"ef32a222-0e58-41da-8b59-b7b49bbfdb64"}}
```

**Comment by jcoglan** [comment] 2016-02-06 12:46
I've never heard anyone experience this problem. Faye itself does not interact with cookies or the session in any way; all of Faye's interaction with the Rack environment is contained in the [RackAdapter](https://github.com/faye/faye/blob/master/lib/faye/adapters/rack_adapter.rb) class if you want to inspect what's going on.

The presence of `ext` fields indicates you're running some extensions but I'm not sure what they are. Those might have access to the Rack environment and could be responsible.

Failing that, I'd need you to put together a test case consisting of a small Rails app containing just enough code to reproduce this problem.

**Comment by jcoglan** [comment] 2016-02-06 12:48
The repeated `/meta/connect` messages are normal. They are not the client 'connecting' as such, only a single WebSocket connection will be being used. Those messages are the part of the Bayeux protocol that's used to poll for new messages. When using a persistent connection transport like WebSocket (as opposed to long-polling), new messages are pushed immediately and the `/meta/connect` messages are just used as a keep-alive mechanism to prolong the client's Bayeux session.

**Comment by toomus** [comment] 2016-02-08 07:43
@jcoglan Thx for reply :) I forgot to say, that I'm not using pure faye gem, but [faye-rails](https://github.com/jamesotron/faye-rails) because it adds some useful features. So maybe the problem is this gem? I found [issue](https://github.com/plataformatec/devise/issues/2939) in Devise repo, where someone has the same problem. What you think about that?

**Comment by jcoglan** [comment] 2016-02-11 21:05
Honestly, I don't know enough about faye-rails or Devise to comment. It's entirely possible that one of those libraries causes an interaction between Faye and the session but I wouldn't know.

**Comment by toomus** [comment] 2016-03-15 08:50
@jcoglan thanks for reply. The cause of all my problems described above was "web-console" gem, which is built in into Rails. Finally the application works fast :)

**Comment by jcoglan** [comment] 2016-05-01 10:39
I'm going to close this since it sounds like you found the source of the problem, but please re-open if you have more questions :)

**Closed by jcoglan** 2016-05-01 10:39 UTC
