### ISSUE TITLE
Bayeux link on the homepage leads to 404

### ISSUE THREAD

**Issue by zeisss** [faye/faye#428] opened 2016-03-09 20:59 UTC
Your homepage at http://faye.jcoglan.com/ contains a link for a Bayeux description at http://svn.cometd.org/trunk/bayeux/bayeux.html - which seem to be no longer available.

**Comment by jcoglan** [comment] 2016-03-17 22:39
This is a duplicate of #413 and is fixed in `master`. The fix will be deployed along with the next release.

**Closed by jcoglan** 2016-03-17 22:39 UTC
