### ISSUE TITLE
WebSocket is already in CLOSING or CLOSED state.

### ISSUE THREAD

**Issue by franck34** [faye/faye#371] opened 2015-03-31 18:48 UTC
Hi Mr Coglan !

I'm using your lib in so many project, thanks for your serious and robust job.

I'm facing on a problem. Screenshot of Chrome console latest version below.

![image](https://cloud.githubusercontent.com/assets/438255/6926257/60e0f304-d7e5-11e4-97b2-7cd3b9d08045.png)

This problem occured only on ONE computer, it's a Windows 8. We tested with Firefox, IE, and Chrome, and same problem with all navigators, but on the same machine. I can't reproduce on my machine, which is a Windows Seven.

Disable firewall: no change
Disable antivirus: no change
MTU test: 1500 on both machine (the one with the problem, the second one without)
Adding a setTimeout of 1 sec for Faye client connect on the JS code: no change

While transport down message occured in the screenshot, i only see handshake debug message server side.

At the moment of the screenshot, we were only 2 using the web application.

Server side: dedicated server with nodeJs, latest version of faye lib.

I would tend  that it's NOT a problem with your libs, i'm just trying to find where come this problem.

I would tend to say that it's related to an extra software installed on the buggy computer. Or a race loading condition (that's why i added a setTimeout for Faye connection, but no change).

I'd like to know if you got a debug method suggestion, this could be a nice page in the wiki  (trouble shooting steps)

Do you have any suggestions please ?

Thanks in advance.

Franck

**Comment by jcoglan** [comment] 2015-04-03 11:04
Do these errors affect the operation of the Faye client? Which line do they come from? The web inspector should display which line in faye-browser.js these errors come from but the line numbers don't appear in your screenshot.

**Comment by franck34** [comment] 2015-04-03 11:47
Yes, the client stop receiving messages.

For line numbers, i'll retake a screenshot this weekend, thank you

**Comment by purian** [comment] 2015-04-14 11:55
Hi James,

We are facing the same problem, I hope that our screenshot will help you to figure out what cause this problem.

Please let me know if you need more information.

![fayesocketproblem](https://cloud.githubusercontent.com/assets/860255/7136116/fa494eda-e2b5-11e4-91d4-4470dfe997b7.png)

**Comment by franck34** [comment] 2015-04-14 11:58
@purian can you provide some details, if possible, regarding the client ? is it IE only ? Windows 8 too ?

**Comment by purian** [comment] 2015-04-14 12:07
@franck34 Sure, It's happen for us on Mac OS X (Mavericks and Yosemite) and Windows 7, On Chrome version  41.0.2272.118 (64-bit) and FF. Probably it's happen on other browser which I have not check yet.

Our faye based on Redis.

Please see Gemfile.lock below:

GIT
  remote: git://github.com/dimelo/faye-redis-ruby.git
  revision: 8b3d7ad858f46c53a131c35f6a0f18ad9eb9c57c
  specs:
    faye-redis (0.2.0)
      em-hiredis (>= 0.2.0)
      eventmachine (>= 0.12.0)
      multi_json (>= 1.0.0)

GIT

GEM
  remote: https://rubygems.org/
  specs:
    addressable (2.3.6)
    capistrano-bundler (1.1.3)
      capistrano (~> 3.1)
      sshkit (~> 1.2)
    colorize (0.7.5)
    cookiejar (0.3.2)
    em-hiredis (0.3.0)
      eventmachine (~> 1.0)
      hiredis (~> 0.5.0)
    em-http-request (1.1.2)
      addressable (>= 2.3.4)
      cookiejar
      em-socksify (>= 0.3)
      eventmachine (>= 1.0.3)
      http_parser.rb (>= 0.6.0)
    em-socksify (0.3.0)
      eventmachine (>= 1.0.0.beta.4)
    eventmachine (1.0.4)
    eventmachine (1.0.4-java)
    faye (1.1.0)
      cookiejar (>= 0.3.0)
      em-http-request (>= 0.3.0)
      eventmachine (>= 0.12.0)
      faye-websocket (>= 0.9.1)
      multi_json (>= 1.0.0)
      rack (>= 1.0.0)
      websocket-driver (>= 0.5.1)
    faye-redis-delayed (0.0.2)
      faye
      faye-redis (>= 0.2.0)
      multi_json (~> 1.0)
    faye-websocket (0.9.2)
      eventmachine (>= 0.12.0)
      websocket-driver (>= 0.5.1)
    foreman (0.77.0)
      thor (~> 0.19.1)
    hiredis (0.5.2)
    hiredis (0.5.2-java)
    http_parser.rb (0.6.0)
    http_parser.rb (0.6.0-java)
    i18n (0.7.0)
    multi_json (1.10.1)
    net-scp (1.2.1)
      net-ssh (>= 2.6.5)
    net-ssh (2.9.1)
    puma (2.11.0)
      rack (>= 1.1, < 2.0)
    puma (2.11.0-java)
      rack (>= 1.1, < 2.0)
    rack (1.6.0)
    rake (10.4.2)
    redis (3.2.0)
    redis-objects (1.0.1)
      redis (>= 3.0.2)
    rvm1-capistrano3 (1.3.2.2)
      capistrano (~> 3.0)
      sshkit (>= 1.2)
    sshkit (1.6.1)
      colorize (>= 0.7.0)
      net-scp (>= 1.1.2)
      net-ssh (>= 2.8.0)
    thor (0.19.1)
    websocket-driver (0.5.1)
      websocket-extensions (>= 0.1.0)
    websocket-driver (0.5.1-java)
      websocket-extensions (>= 0.1.0)
    websocket-extensions (0.1.1)

PLATFORMS
  java
  ruby

DEPENDENCIES
  faye
  faye-redis!
  faye-redis-delayed
  foreman
  puma
  redis-objects

**Comment by franck34** [comment] 2015-04-15 14:18
The end user who note this bug think about an inactivity timeout problem on the websocket.

**Comment by purian** [comment] 2015-04-16 11:07
Hi,
For our browsers it's happen few seconds after the page is loaded sometime even less than a second.

**Comment by franck34** [comment] 2015-04-16 12:47
same here

**Comment by franck34** [comment] 2015-04-20 07:32
Here is line on my side (the same)

![bugfaye](https://cloud.githubusercontent.com/assets/438255/7225538/e9852ed2-e73f-11e4-9a02-745df0d5097e.png)

**Comment by franck34** [comment] 2015-04-20 07:33
@jcoglan hi ! any idea ?

**Comment by purian** [comment] 2015-04-26 08:10
@jcoglan Hi, do you need more information from our side to investigate this issue?

**Comment by jcoglan** [comment] 2015-04-27 09:22
I'm not working on Faye at the moment as I'm busy with other projects. It looks like [this code](https://github.com/faye/faye/blob/master/javascript/transport/web_socket.js#L20-L24) is yielding a closed socket. This is supposed not to happen due to [the onclose handler](https://github.com/faye/faye/blob/master/javascript/transport/web_socket.js#L65) but clearly something is going wrong there.

I've not had other reports of this issue and can't reproduce it myself but there's where you should start investigating.

**Comment by franck34** [comment] 2015-05-02 20:00
thank you @jcoglan 
@purian i'm not able to reproduce myself (no problem with my computer), can you ?

**Comment by alexandrevicenzi** [comment] 2015-05-12 17:32
I have this issue when internet goes down. It's logging many times, but when I get internet again it works fine.

**Comment by jcoglan** [comment] 2015-05-13 07:56
@alexandrevicenzi That sounds like normal behaviour to me. Bear in mind that the browser will print warnings about various things and you cannot silence these with JavaScript. i.e. they are not uncaught exceptions or error events.

**Comment by alexandrevicenzi** [comment] 2015-05-13 13:29
@jcoglan as I said, it works fine to me, I just reported to see if its normal or not. 

Thanks :+1:

**Comment by purian** [comment] 2015-05-18 09:19
@franck34 Sorry for the late response, I was out of the office.
We still having this issue, Do you want some information?

**Comment by franck34** [comment] 2015-05-18 10:45
@purian hi. In fact, on my computer i don't have any problem, so i am not able to reproduce so can't go deeper into code troubleshooting. Do you have a computer on which you can reproduce systematically ? if yes are you ok for a webex or something like that ?

**Comment by purian** [comment] 2015-05-18 11:08
@franck34 hi, We have online app that currently have this problem, I can give you access to it.
How can I reach you in private channel?

**Comment by franck34** [comment] 2015-05-19 07:44
@purian available on freenode (#node.js) nick franck34

**Comment by purian** [comment] 2015-05-19 08:32
@franck34 Hey, I tried to reach you there but without success

**Comment by franck34** [comment] 2015-05-19 10:34
sorry i'm busy right now, please send me a mail to franck tab (at) gmail dotoo com so we take a rendez vous, thanks !

**Comment by jcoglan** [comment] 2015-07-05 18:28
Sorry for my delay in responding to this. I just pushed https://github.com/faye/faye/commit/295798ce3075d646e74875dd112fc7e7d1a1e2a9 which attempts to fix it. I think this is what's going on:

1. [The transport calls `callback`][1] to try to get a WebSocket. There might be one already connected.
2. [`callback` uses `Promise.then()`][2] to retrieve the cached connection. `Promise.then()` invokes functions asynchronously
3. Between the call in (2) and the [callback function][3] being invoked, the socket is closed.

Checking the socket's `readyState` should be sufficient. If the socket was closed, then the transport should reopen it and [retry][4] the [pending][5] messages.

Can someone let me know if this fixes the problem?

[1]: https://github.com/faye/faye/blob/295798ce3075d646e74875dd112fc7e7d1a1e2a9/javascript/transport/web_socket.js#L20
[2]: https://github.com/faye/faye/blob/295798ce3075d646e74875dd112fc7e7d1a1e2a9/javascript/mixins/deferrable.js#L17
[3]: https://github.com/faye/faye/blob/295798ce3075d646e74875dd112fc7e7d1a1e2a9/javascript/transport/web_socket.js#L20-L24
[4]: https://github.com/faye/faye/blob/295798ce3075d646e74875dd112fc7e7d1a1e2a9/javascript/transport/web_socket.js#L71
[5]: https://github.com/faye/faye/blob/295798ce3075d646e74875dd112fc7e7d1a1e2a9/javascript/transport/web_socket.js#L16

**Comment by franck34** [comment] 2015-07-06 06:02
Hi !

I'll test it asap, thanks a lot

**Comment by franck34** [comment] 2015-07-16 20:40
Testing right now

**Comment by franck34** [comment] 2015-07-16 21:54
No way. But i've got more interesting informations.

2 computers. Windows Seven, 64 bits.

Same browser (latest chrome 64 bits)

Below logs for the computer which is working perfectly:

![fayeok](https://cloud.githubusercontent.com/assets/438255/8736051/b995f984-2c15-11e5-952e-6a01817897dc.png)

Below logs for the computer which is NOT working:

![fayebad](https://cloud.githubusercontent.com/assets/438255/8736063/c9b1ec56-2c15-11e5-89a6-839069c38757.png)

MTU is the same on both computers, same browser, same OS. I'm sure theses informations will help @jcoglan ;)

Have an idea ?

Thanks a lot

**Comment by franck34** [comment] 2015-07-16 21:59
mm sorry, the computer having a problem is a Windows 8, not 7

**Comment by jcoglan** [comment] 2015-07-17 07:54
@franck34 Those screenshots look like normal behaviour to me.

**Comment by franck34** [comment] 2015-07-17 11:03
The connection type is long polling in a first time for the computer which does not work. Notice in the second screenshot "transport down" at the end

**Comment by jcoglan** [comment] 2015-07-17 18:41
It's normal and common for the first `/meta/connect` message to be sent via `long-polling`; it depends on whether a WebSocket connection has successfully been established yet, which is in a race with the handshake request for which one finishes first.

It's not the cause of the `transport:down`; notice you get a reply to the message with `id: "2"` sent via `long-polling`.

**Comment by jcoglan** [comment] 2015-07-17 18:42
Is your client still producing WebSocket errors? Is it still unable to receive messages? What about if you disable the `websocket` transport?

**Comment by franck34** [comment] 2015-07-28 09:07
Hi

On the bad computer: 
* if i disable long polling, i've got "transport:up" and then "transport:down" followed by "WebSocket is already in CLOSING or CLOSED state." error.
* if i disable websocket, i've got "transport:up", no "transport:down", but message sent by the server are not received by the browser. i can see in the console regular POST requests, but none of them contains data sent (only advice messages)

In both case (with or without js error), messages with data are not received by the bad computer. I can not reproduce this behavior using another computer(s), everything is normal.

Server side, i can see the handshake followed by the subscription, the behavior is the same between good/bad computer.

I begin to think that it's really related to this fucked computer, but i can't find why exactly.

I created a VMWare Windows Guest on the fucked computer and i've use same chrome version .... it's working ... really strange.

**Comment by lgwaustralia** [comment] 2015-08-06 06:44
Hi Franck, I can report I am getting faye-browser.js:2289 WebSocket is already in CLOSING or CLOSED state. errors also.  They seem intermittent.  Chrome Version 46.0.2471.2 dev (64-bit) on mac 10.9.5 
faye@1.1.1

**Comment by franck34** [comment] 2015-09-02 06:13
The best workaround i've found is to disable websocket like that, client side:

    Faye.Transport.WebSocket.isUsable = function($, _, c) { c(false) };


Content type is now text/event-stream and it's "ok" for me. 

I can't find a good explication. I've just notice that the fucked computer is really slow and testing websocket with https://www.websocket.org/echo.html using latest chrome browser ... fail !

**Comment by jflowers45** [comment] 2015-10-19 22:11
we're having the same problem.  but we traced it down to the _ping function ... see screenshot  Maybe it's running on an interval and the socket exists (and passes the this._socket test) but is closed?

![fayeping](https://cloud.githubusercontent.com/assets/1021048/10592810/8a5c3996-768c-11e5-9fc6-13ae1e5abea2.png)

**Comment by jcoglan** [comment] 2015-10-20 20:56
@jflowers45 Thanks for that. Does https://github.com/faye/faye/commit/72a6d4d2fcfc4e8be730892ca0109dd09d96b5fa fix the issue for you? What about everyone else?

**Comment by jflowers45** [comment] 2015-10-29 16:28
@jcoglan still happens in the 'request' function as well - we tried using the same check you use on _ping but it seemed to stop it from functioning altogether ... does that make sense?
<img width="927" alt="requestfunction" src="https://cloud.githubusercontent.com/assets/1021048/10824826/7ad4b5e4-7e38-11e5-9a80-ec070ba37d7e.png">

**Comment by jcoglan** [comment] 2015-11-07 12:06
@jflowers45 The code in your console doesn't match the latest release, which already has a `readyState` check in `request()`:

https://github.com/faye/faye/blob/1.1.2/javascript/transport/web_socket.js#L21

Can you try with the latest release or `master`?

**Comment by jflowers45** [comment] 2015-11-23 22:15
@jcoglan FYI we recently realized this started happening when we lowered the Faye timeout from the 45 second default to be 5 seconds.  We did this because we're using faye on pages that google crawls and it was giving us warnings about slow response times before we changed that timeout on them.  We're hoping to find a middle ground where Google doesn't complain and also where we don't see the error.  Anyways - maybe that will provide you some context for the future.

This might be a dumb question ... but how would I go about installing master?  it seems to be slightly out of sync with the version I can install via NPM (that one doesn't have the _ping fix)

Also, I can just change the line of code ... but I was curious if there is an obvious way to 'compile' the github repo into the format we normally get from NPM

**Comment by matthisk** [comment] 2016-02-22 12:52
@jcoglan The fix from 72a6d4d seems to fix our issues we had with `WebSocket is already in CLOSING or CLOSED state` is there any chance this can be released to the npm package as a patch or minor version?

**Comment by jcoglan** [comment] 2016-02-23 08:47
@matthisk My priority at the moment is getting 1.2 released, which has a couple of incomplete feature branches that need to get merged before we can do that. Hopefully I'll have some time in the next few weeks to see to that.

**Comment by matthisk** [comment] 2016-03-02 10:08
@jcoglan we have been using this fix in production for a while now by hot patching it in our build javascript file and any issues we had regarding long running websocket connections have gone away. Now I was trying to install faye as an npm dependency directly from commit hash 72a6d4d but that doesn't seem to work? We have clients depending on the Faye JS client who are still experiencing this issue and would really like a solution, but want to avoid forking the library and creating our own package on NPM. Any update on the timeframe on this?

**Comment by jcoglan** [comment] 2016-03-17 22:42
@matthisk Faye currently requires a build step to create the package from source -- you need to run `npm run build` from the root of the repo.

This will change in the next major release, which will migrate to standard node modules for everything and generate the browser client with webpack.

Unfortunately as I work on Faye in my spare time, I'm unable to make any promises about when the current work in progress will be finished ready for release.

I'm going to close this issue since the error it describes seems to be  fixed.

**Closed by jcoglan** 2016-03-17 22:42 UTC

**Comment by jcoglan** [comment] 2016-03-17 22:44
@matthisk Watch for the `node-modules` branch to land on `master`, then you should be able to install directly from git.

**Comment by franck34** [comment] 2016-03-17 22:54
@jcoglan thank you james

**Comment by MaxPleaner** [comment] 2017-02-23 19:39
This doesn't solely have to do with faye, but I stumbled across this and thought to share my 2 cents.

This error doesn not not necessarily a server-side concern; you will get it if your wifi re-opens or something like that. A way to address this is to make the Javascript websocket client's `close` trigger attempt to reconnect on a loop

**Comment by PierrePika** [comment] 2017-03-21 22:25
Hi, i had a similar problem. Websocket connection was opening and directly closing. The problem came from client side.
I had the connection opening in a function executed once the DOMContentLoaded event occurs. The websocket var was defined outside of these function scope. Once i have supressed these definition outside of the scope it was working.

Works

document.addEventListener('DOMContentLoaded', function () {
    initialiseWebSocket("ws://localhost:9000/cupcake/core/webSocketServerCore/server.php");
});

function initialiseWebSocket(url){
    websocket = new WebSocket(url);
    websocket.onopen = function(ev) { // connection is open 
        alert('sucessful connected');
    };
    websocket.onmessage = function(ev) {
        var msg = JSON.parse(ev.data); //PHP sends Json data
        processServerMessage(msg);
    };
    websocket.onerror= function(ev){alert('error');}; 
    websocket.onclose= function(ev){alert('connection closed');}; 
}

Dont Work

var websocket;

document.addEventListener('DOMContentLoaded', function () {
    initialiseWebSocket("ws://localhost:9000/cupcake/core/webSocketServerCore/server.php");
});

function initialiseWebSocket(url){
    websocket = new WebSocket(url);
    websocket.onopen = function(ev) { // connection is open 
        alert('sucessful connected');
    };
    websocket.onmessage = function(ev) {
        var msg = JSON.parse(ev.data); //PHP sends Json data
        processServerMessage(msg);
    };
    websocket.onerror= function(ev){alert('error');}; 
    websocket.onclose= function(ev){alert('connection closed');}; 
}
