### ISSUE TITLE
Updating to 1.2.2 with Chrome time throttling

### ISSUE THREAD

**Issue by justindujardin** [faye/faye#447] opened 2016-07-29 17:33 UTC
### Problem

Recent versions of Chrome browser throttle time callbacks to pages when in the background or when the tab is not active. This resulted in frequent websocket disconnects on `1.1.2`, so we monkey patched the `Faye.Transport.WebSocket.prototype._ping` method to receive time updates from a WebWorker (which is not subject to time throttling.) 

While updating to `1.2.2` to get the fix from #394, it became apparent that our patch of WebSocket ping will no longer work because `Faye.Transport.WebSocket.prototype` is no longer exposed.
### Question

Can you recommend a method for providing reliable time updates to the WebSocket._ping method without the monkey patch that was used in `1.1.2`?

Because Faye now [checks the readyState](https://github.com/faye/faye/blob/1.2.1/src/transport/web_socket.js#L128) of the socket while pinging, I think the only thing I really _need_ is the custom timeout function bit.
### Existing 1.1.2 Patch

``` typescript
// Based on official method: https://github.com/faye/faye/blob/1.1.2/javascript/transport/web_socket.js#L113-L117
Faye.Transport.WebSocket.prototype._ping = function () {
  let self: any = this;
  if (self._socket) {
    let socket = self._socket;
    let state = socket.readyState;
    if (state === socket.CLOSED || state === socket.CLOSING) {
      return;
    }
    else {
      self._socket.send('[]');
    }
    time.wait(pingDelay, () => self._ping()); // schedule the next
  }
};
```

**Comment by jcoglan** [comment] 2016-07-30 14:14
I'm not sure what you mean by 'time callbacks' or 'time updates'. Can you clarify what the problem is, and how your patch fixes it?

**Comment by justindujardin** [comment] 2016-07-31 15:47
`global.setTimeout` is used internally in Faye.  When running in Chrome, and not the active tab, the callback functions for `setTimeout` and `setInterval` are not invoked on time. A setTimeout call with a 500ms delay may have its callback invoked 5 seconds later. This presents a problem for Faye because over time the ping messages become further and further behind and eventually the client connection is terminated.

The patch I applied delegates the `setTimeout` calls to a custom class that posts a message to a webworker. The worker sets the timeout and then posts back to the main thread when it is complete.  WebWorkers are not subject to the throttling of "time" callbacks (i.e. setTimeout, setInterval.) This allows the client to deliver timely pings to the server, making the websocket connection much more reliable.

**Comment by sterpe** [comment] 2016-07-31 17:07
What about requestAnimationFrame or window.postMessage to count ticks...are those throttled too?

**Comment by jcoglan** [comment] 2016-07-31 18:23
If you're using Browserify, Webpack or similar build tool you can access the WebSocket transport like this:

```js
var wsTransport = require('faye/src/transport/web_socket');
```

As of 1.2, Faye is distributed as the actual source tree of Node modules, rather than as one big blob, so you can still access individual classes within that tree.

**Comment by mirekm** [comment] 2016-08-11 13:04
@justindujardin Thanks for sharing your earlier solution. Have you eventually came up with some fix addressing the issue for the 1.2?

**Comment by AleksandrLeontev** [comment] 2016-08-11 15:21
Still have this problem: "Uncaught TypeError: Cannot read property '_state' of undefined"
And also faye mount for me 1.1.1 client JS library, but I use faye 1.2.2

**Comment by jcoglan** [comment] 2016-08-11 16:00
@AleksandrLeontev Your comment doesn't seem related to this issue -- can you open a new one to avoid spamming the other people in this thread?

The `_state` problem is #394 which was fixed in 1.2.0. I'm not sure why you're still getting a 1.1 client but if you have details that would help me reproduce this issue, please open a new issue.

**Comment by mirekm** [comment] 2016-08-11 19:24
Also, shouldn't the issue in question be handled by longer timeout (on both server and client)? As far as I understand, the `_ping` method tiggered by `setTimeout` will be eventually called on the browser when the tab is inactive but just in a little less predictable manner and later than normally?

**Comment by AleksandrLeontev** [comment] 2016-08-12 08:54
@jcoglan yes, sorry. it was my mistake.
I just replace gem declaration from master branch to stable repo.
gem 'faye', github: 'faye/faye' ->  gem 'faye'

yes, #394 works for me now, thanks.

**Comment by jcoglan** [comment] 2016-10-11 20:08
I'm not sure where we got to with this issue. Does it require more attention from me, or should I close it?

**Comment by justindujardin** [comment] 2016-10-11 23:51
@jcoglan I do not currently use a module bundler, and I'd prefer not to have to rewrite my build automation to apply the workaround you suggested.

I'd like to hear your thoughts on allowing users to provide a custom implementation for `src/mixins/timeouts.js`. This seems like it would be minimally invasive, and would allow me to provide my WebWorker based timeout implementation on the client side.

**Comment by jcoglan** [comment] 2016-11-15 21:56
Apologies for the delay, but a thought occurs to me: if code in WebWorkers does not have its timers throttled, can you run your whole Faye client in a worker rather than patching its internals? The patch is inherently brittle because it's replacing an implementation detail.

The `_ping()` method is not essential functionality -- it's a hack designed to keep the connection open. Are there other ways we could achieve this?

**Comment by jcoglan** [comment] 2017-01-28 14:41
@justindujardin I never heard back in response to my last question -- do you have any thoughts on my suggestion?

**Comment by justindujardin** [comment] 2017-01-28 16:40
@jcoglan I've been busy at work and this upgrade fell off my radar. 

I think your suggestion to run in a worker is great. Have you tested Faye with WebWorkers before?

**Comment by jcoglan** [comment] 2017-01-28 17:03
1.2.0 speficially fixed a bunch of problems so that Faye can run inside WebWorkers.

**Comment by justindujardin** [comment] 2017-01-28 17:11
That's great. Feel free to close this issue.

**Closed** 2017-01-28 17:43 UTC
