### ISSUE TITLE
Using polling with a "large" payload fails

### ISSUE THREAD

**Issue by jornki** [faye/faye#361] opened 2015-02-03 11:00 UTC
> Note that this problem is not reproducible when WebSockets are available.

* Node.js server
* Faye version 1.1.0
* Tested in Chrome and Safari

WebSockets have been disabled (to test the other methods) by setting `client.disable('websocket')`. This results in Faye using polling, in my case, over https.

When passing a payload of more than 2048 chars to `client.publish("/mychannel", "more than 2048 chars")` the Faye server is not notified and the request is stuck in a retry loop.

> To recreate simply pass an object (or a string) to `client.publish` which results in a string larger than 2048 characters.

Is this expected behavior, in other words, doesn't Faye support payloads larger than 2048 chars over xhr or do you consider this a bug?

_Speculation_
When debugging the exception occurs in the `_fulfill` method (line 470) of the Faye client. The passed promise is undefined which yields a `TypeError: Cannot read property '_state' of undefined`.

As far as I can see this originates in `_flushLargeBatch`, since `string.length` is larger than `this._dispatcher.maxRequestSize`.

**Comment by jcoglan** [comment] 2015-02-06 21:10
This is expected behaviour; there's a [limit](https://github.com/faye/faye/blob/4841e022b489478e0eddda6965177a6e20c5444c/javascript/protocol/dispatcher.js#L2) on the size of request URLs/bodies when using polling transports.

I think this is substantially below the limit of most web servers. If you can't make your messages any smaller, you can currently override this setting by:

```js
Faye.Dispatcher.prototype. MAX_REQUEST_SIZE = newMaxSize;
```

**Comment by jornki** [comment] 2015-02-06 21:40
Thanks. I'll try to override the ´MAX_REQUEST_SIZE´.

One question though.
The Faye `MAX_REQUEST_SIZE` is referring to the size of the POST body right, not the length of the URL? I think the length of URLs have a stricter limit on most web servers.

**Comment by jcoglan** [comment] 2015-02-06 21:46
It's used for both request URLs and bodies -- some transports use POST and others use GET.

**Comment by jornki** [comment] 2015-02-06 22:55
Ok, thanks.

**Comment by jcoglan** [comment] 2015-02-19 13:17
Should I close this or is there work needed to resolve it?

**Comment by jornki** [comment] 2015-02-19 13:51
I'm sorry. The MAX_REQUEST_SIZE did fix the issues, so you can close this.

**Closed** 2015-02-19 14:02 UTC

**Comment by mirekm** [comment] 2016-02-02 13:30
Hi guys,

What if we don't want to change the limits but handle this exception ourselves. Shouldn't this call error callback instead of throwing the exception?

**Comment by jcoglan** [comment] 2016-02-07 13:16
@mirekm Could you explain more about your specific use case so we can understand why you want to handle this error yourself? There might be a solution that better fits Faye's design.

Historically, error handling has been the hardest part of Faye to get right, and there is a significant amount of internal code dedicated to error handling and recovery. Since there's a lot of indirection between you calling `publish()` and the message actually being sent to the server, exposing part of this mechanism to user control is likely to introduce significant complexity and bugs.

The design direction of Faye is that we would much rather that errors are handled transparently if at all possible -- the goal is to take complicated stuff like this out of your application code. So for example we'd much rather introduce new config to control internal mechanisms than introduce new ways to inject arbitrary code into the client's processes.

One final note -- would you mind not using 'guys' to address people within this project -- it's gendered and can exclude women and non-binary people. Consider "everyone", "folks", "people", "all", "team", for example instead :)
