### ISSUE TITLE
faye browser client is pretty huge

### ISSUE THREAD

**Issue by tbarbugli** [faye/faye#403] opened 2015-09-23 02:38 UTC
84KB the not minified and 40KB for the minified. are there any modules that are easy to exclude from the build?

**Comment by jcoglan** [comment] 2015-10-01 06:40
I probably have a blind spot on this front; the one thing I would like to remove is the JSON module that's bundled to support old browsers. However last I tried to do this I ran into compatibility issues with the JSON module in some browsers, which can't deal correctly with objects that implement `toJSON()` incorrectly (which causes issues with Prototype and Mootools).

Have you looked through the client code? Does any of it seem redundant to you?

**Comment by tbarbugli** [comment] 2015-10-01 16:43
removing the JSON module was my first idea too :(

**Comment by jcoglan** [comment] 2015-10-02 18:03
It may be possible to remove it and provide instructions for fixing things using `json2.js` if you have problems. The issue is that, to avoid Prototype or Mootools breaking JSON encoding, you have to call:

```js
JSON.stringify(value, function(key, value) {
  return this instanceof Array ? this[key] : value;
});
```

However, some browsers' JSON implementation lacks support for the second functional argument, and `json2.js` out of the box will not install its own implementation if `window.JSON` already exists. This is why Faye bundles a modified copy of it and puts the `stringify()` function in the `Faye` namespace, to make sure it's available.

So it might be that this isn't an issue any more, but if it is, you have to import json2.js and hack its source code to replace `window.JSON`, which is a terrible user experience.

Does anything else look like it could be removed to you?

**Comment by thesmart** [comment] 2015-10-06 21:27
Maybe Faye.Promise should follow ES6 Promise and rely on a polyfill for the short term?

Also, I think at this point WebSockets are so standard that longpolling could be deprecated.

**Comment by thesmart** [comment] 2015-10-07 02:35
Breaking support for Mootools and Prototype:
https://github.com/faye/faye/pull/405/files

**Comment by jcoglan** [comment] 2015-10-18 12:10
I think the footprint of Faye's Promise class is pretty small and Promise isn't yet widespread enough that removing our implementation wouldn't be an annoying user experience problem.

I'm comfortable with removing JSON and we should continue that conversation in #405.

WebSocket being standard is not the issue. The problem is that even if the browser has it, it might not work for other reasons:

* The target server does not support it
* There is a proxy between the client and server that does not support it
* There is a bug in the client or server or both

For example: Firefox diverges from the spec for the `permessage-deflate` extension by rejecting a server handshake that contains the `server_max_window_bits` parameter. This means that if the server conforms to spec and the server operator sets a window size limit, then WebSocket won't work in Firefox (https://github.com/faye/permessage-deflate-ruby/pull/1). (This causes a knock-on issue in Faye for unrelated reasons: https://github.com/faye/faye/pull/398.)

So the Bayeux spec says that clients must always handshake using something guaranteed to work (like long-polling) and only upgrade to better transports if they can confirm that transport will work. Faye will continue to go by this and default to long-polling.

Unless we can identify anything else we should cull from the client I'm going to focus on the JSON issue in #405 and close this thread.

**Comment by jcoglan** [comment] 2016-05-19 22:03
I'm going to close this in light of my comments above. JSON has been removed now we've moved to using Node-style modules for the client. I've looked into using a third-party Promise library but most of the big ones make the Faye client even bigger than it is now.

**Closed by jcoglan** 2016-05-19 22:03 UTC
