### ISSUE TITLE
Promise returned from client.subscribe() does not include message from server as a parameter

### ISSUE THREAD

**Issue by shawn-simon** [faye/faye#400] opened 2015-08-28 07:36 UTC
This would allow you to populate the channel with the current state. The current workaround is an extension that's super ugly code-wise, and I'm not sure if it's even possible. You'd have to wrap the entire library and maintain lots of state.

```
       client.subscribe('/foo', function(message) {
          // message is defined
        }).then(function(message) {
            // message is undefined
        })
```

**Comment by chunnerslee** [comment] 2015-08-28 08:19
+1

**Comment by jcoglan** [comment] 2015-10-18 15:29
The promise returned by `Client.subscribe()` does not yield the server's response because there might not be one, or there might be many.

If the client is already subscribed to the channel, then we just need to store the new callback, and we don't need to send anything to the server. In this event, the promise should be fulfilled, because the subscription is successful, but there's no server response to fulfil it with.

If the client becomes disconnected from the server for a sustained length of time, then the client will need to re-establish its subscriptions with the server. It does this transparently without the user needing to do anything. In this event, we do sent requests to the server and get responses, and the user needs to process those responses: if you've been offline for a while you need to refresh from the state the server sent you, because you may have missed messages. However, these re-subscription responses cannot be passed to the promise from your original `subscribe()` call, because it has already been fulfilled. Promises are not multi-event values, they resolve only once.

So the general reason is there's not a one-to-one correspondence between `Client.subscribe()` calls and requests to the server, and the former is not intended to be an abstraction of the latter. The purpose of `Client` is to hide the details of the wire protocol, in part to enable features like this without coupling the application to the Bayeux protocol.

The "workaround" you mention is actually the intended way of doing what you want: extensions *are* coupled to what goes over the wire, and so they're the proper place to handle anything that needs to be done whenever you need to establish a subscription via the server.

I'm not sure what you mean by having to "wrap the entire library and maintain lots of state". It is good to decouple your application from your messaging implementation somewhat and so some indirection will be necessary. But the minimum code you need to do this type of thing is:

```js
client.subscribe('/channel', function(message) {
  updateState(message);
});

client.addExtension({
  incoming: function(message, callback) {
    if (message.channel === '/meta/subscribe' && message.subscription === '/channel' && message.successful) {
      resetState(message.ext.state);
    }
    callback(message);
  }
});
```

... plus a little code on the server to set `message.ext.state` to contain the channel's state. Are you running into issues that require much more code than this?

**Comment by jcoglan** [comment] 2015-11-07 11:44
Did my response make sense? Do you have further questions about this or can I close the issue?

**Comment by shawn-simon** [comment] 2015-11-08 04:10
In the code you posted, message will always be undefined. that is the bug I was reporting, unless it's been fixed by now. I'm not using faye anymore however, because I'm convinced the bayeux protocol is not suitable for real applications

**Comment by jcoglan** [comment] 2015-11-08 12:38
In that case, it's not a bug, it's by design, as I laid out above.

I don't mind if you decided to go with another solution, whatever your reason, but in future I'd ask that you not leave passive-aggressive remarks like "not suitable for real applications" on other people's projects, especially when they've taken the time to explain the problem with what you're asking for, and suggesting other ways to solve your problem.

**Closed by jcoglan** 2015-11-08 12:38 UTC

**Comment by shawn-simon** [comment] 2015-11-09 07:53
Ahh, sorry : ( I see how your snippet works now. Apologies for coming off that way. I feel like having to use the server as just a relay for the clients without any way to modify the data between calls creates situations like this. I can't see a use case where you would prefer this to sending data and getting acknowledgement callbacks with data, in addition to the events sent in the channels.
