### ISSUE TITLE
All the clients are not getting subscribed to channel

### ISSUE THREAD

**Issue by vikas17a** [faye/faye#388] opened 2015-06-24 11:29 UTC
I fired a faye server with redis as faye engine [server code](https://gist.github.com/vikas17a/888e1c2f9977410878da) with one subscriber and one publisher both on different machine [subscriber code](https://gist.github.com/vikas17a/75f2b72260f4b825a6b4) after firing  subscriber script the results i got on faye server terminal is 
```
client : 4999
client : 5000
client subscribed : 4304
client subscribed : 4305
client subscribed : 4306
client subscribed : 4307
client subscribed : 4308
client subscribed : 4309
```

**Comment by jcoglan** [comment] 2015-07-05 15:17
I'm not really sure what you're trying to do here by opening thousands of clients in the same process, subscribed to the same channel. If if you slow the client code down using a `setInterval` loop, it still hits a limit caused by Thin's connection limit, and it is possibly hitting the per-process file descriptor limit in the operating system.

**Comment by vikas17a** [comment] 2015-07-16 13:19
I am testing out how many clients can actually subscribe to faye pub-sub server, i am trying out different pub-sub models and faye is one of them. I already increased the no of open file descriptor limit to ```64k``` on both faye server as well as faye client, but still i am not able to subscribe all the clients connected to faye server.
I am trying this out to test how many concurrent subscribers can subscribe to faye-server on one node and based on it i will set up my pub-sub model in one of my upcoming projects to handle 50K concurrent subscribers

**Comment by jcoglan** [comment] 2015-07-17 18:44
Launching thousands of connections instantaneously from the same process on the same machine doesn't seem like a reasonable way to benchmark this sort of thing. All those clients in the same process will be contending for file descriptors and CPU time on the Node event loop.

**Comment by jcoglan** [comment] 2016-05-30 17:34
Do you have any further feedback on my last comment, or should I close this issue?

**Comment by jcoglan** [comment] 2016-06-21 21:01
I'm going to close this issue due to lack of feedback. If you do have any further comments, please do re-open :)

**Closed by jcoglan** 2016-06-21 21:01 UTC
